# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# COPY THIS FILE TO shopify.app.toml AND FILL IN YOUR ACTUAL VALUES

client_id = "your_shopify_app_client_id_here"
name = "ihear.ai"
handle = "ihear-ai"
application_url = "https://your-tunnel-url.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://your-tunnel-url.trycloudflare.com/auth/callback",
  "https://your-tunnel-url.trycloudflare.com/auth/shopify/callback",
  "https://your-tunnel-url.trycloudflare.com/api/auth/callback"
] 